# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Results(object):
    def setupUi(self, Results):
        Results.setObjectName("Results")
        Results.resize(763, 571)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        Results.setFont(font)
        self.label_7 = QtWidgets.QLabel(Results)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.indi_table = QtWidgets.QTableView(Results)
        self.indi_table.setGeometry(QtCore.QRect(0, 350, 761, 192))
        self.indi_table.setObjectName("indi_table")
        self.label_8 = QtWidgets.QLabel(Results)
        self.label_8.setGeometry(QtCore.QRect(20, 300, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.listView = QtWidgets.QListView(Results)
        self.listView.setGeometry(QtCore.QRect(0, 60, 761, 192))
        self.listView.setObjectName("listView")

        self.retranslateUi(Results)
        QtCore.QMetaObject.connectSlotsByName(Results)

    def retranslateUi(self, Results):
        _translate = QtCore.QCoreApplication.translate
        Results.setWindowTitle(_translate("Results", "Results"))
        self.label_7.setText(_translate("Results", "Generaciones"))
        self.label_8.setText(_translate("Results", "Individuos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Results = QtWidgets.QDialog()
    ui = Ui_Results()
    ui.setupUi(Results)
    Results.show()
    sys.exit(app.exec_())
